# Generated by Django 2.1.3 on 2018-11-05 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('place_of_birth', models.CharField(max_length=20)),
                ('date_of_birth', models.DateTimeField()),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=16)),
            ],
        ),
    ]
