# Generated by Django 2.1.3 on 2018-11-06 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestDjango', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dosen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosen_id', models.CharField(default='DOSEN_0001', max_length=100)),
                ('dosen_name', models.CharField(max_length=100)),
                ('dosen_tempat_lahir', models.CharField(default='SOME STRING', max_length=140)),
                ('dosen_address', models.TextField()),
                ('dosen_phone', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Kelas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.CharField(default='KELAS_0001', max_length=100)),
                ('class_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='date_of_birth',
        ),
        migrations.AddField(
            model_name='student',
            name='student_id',
            field=models.CharField(default='STUDENT_0001', max_length=100),
        ),
    ]
