# Generated by Django 2.1.3 on 2018-11-06 07:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestDjango', '0002_auto_20181106_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='dosen',
            name='dosen_date_of_birth',
            field=models.DateField(default=datetime.datetime(2018, 11, 6, 14, 24, 34, 376446)),
        ),
        migrations.AlterField(
            model_name='dosen',
            name='dosen_tempat_lahir',
            field=models.CharField(default='', max_length=140),
        ),
    ]
