# Generated by Django 2.1.3 on 2018-11-06 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestDjango', '0003_auto_20181106_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosen',
            name='dosen_date_of_birth',
            field=models.DateField(default='1990-01-01'),
        ),
    ]
