# Generated by Django 2.2.1 on 2019-05-31 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestDjango', '0005_student_date_of_birth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dosen',
            old_name='dosen_address',
            new_name='alamat',
        ),
        migrations.RenameField(
            model_name='dosen',
            old_name='dosen_name',
            new_name='nama_dosen',
        ),
        migrations.RenameField(
            model_name='dosen',
            old_name='dosen_date_of_birth',
            new_name='tanggal_lahir',
        ),
        migrations.RenameField(
            model_name='dosen',
            old_name='dosen_phone',
            new_name='telepon',
        ),
        migrations.RenameField(
            model_name='dosen',
            old_name='dosen_tempat_lahir',
            new_name='tempat_lahir',
        ),
    ]
