# Generated by Django 2.2.1 on 2019-05-31 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestDjango', '0006_auto_20190531_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(default='19.11.0001', max_length=100),
        ),
    ]
