# Generated by Django 2.2.1 on 2019-05-31 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestDjango', '0007_auto_20190531_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='kelas',
            field=models.CharField(default='', max_length=51),
        ),
    ]
